allowBuilds:
  esbuild: false
  lefthook: false
ignoredBuiltDependencies:
  - esbuild
  - lefthook
minimumReleaseAgeExclude:
  - '@unterberg/vite-beasties-output@0.1.2'
minimumReleaseAgeStrict: false
onlyBuiltDependencies:
  - "@biomejs/biome"
